-- MySQL schema for Lucky Draw

CREATE TABLE IF NOT EXISTS karyawan (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nama VARCHAR(191) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS gift (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	urut INT NOT NULL,
	nama_hadiah VARCHAR(191) NOT NULL,
	is_assigned TINYINT(1) NOT NULL DEFAULT 0,
	PRIMARY KEY (id),
	UNIQUE KEY uniq_urut (urut)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS winners (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	karyawan_id INT UNSIGNED NOT NULL,
	gift_id INT UNSIGNED NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE KEY uniq_winner_karyawan (karyawan_id),
	UNIQUE KEY uniq_winner_gift (gift_id),
	CONSTRAINT fk_winner_karyawan FOREIGN KEY (karyawan_id) REFERENCES karyawan(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT fk_winner_gift FOREIGN KEY (gift_id) REFERENCES gift(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed 20 gifts if table empty
INSERT INTO gift (urut, nama_hadiah, is_assigned)
SELECT seq.num AS urut, CONCAT('Hadiah ', LPAD(seq.num, 2, '0')) AS nama_hadiah, 0
FROM (
	SELECT 1 AS num UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
	UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
	UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15
	UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20
) AS seq
LEFT JOIN gift g ON g.urut = seq.num
WHERE g.id IS NULL;